# Site settings
#
title: Roger is an engineer at 18F
email: hi@rog.gr
description: > # this means to ignore newlines until the next stanza.
  I'm Roger Steve Ruiz. I contribute to open source software at
  [18F](https://18f.gsa.gov) building user-centered digital services
  and the [&#x2601;&#xFE0F;](https://cloud.gov).
goodbye_message: >
  Thanks for stopping by. &#x1f44b;&#x1f3fd;
baseurl: ""
url: "http://write.rog.gr"
twitter_username: rogeruiz
github_username: rogeruiz

permalink: /:title.html

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md

include:
  - bower_components/

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: [ "writing" ]
      permalink: /writing/:title.html
  -
    scope:
      path: "dress-code"
      type: "posts"
    values:
      categories: [ "dress-code" ]
      permalink: /dress-code/:title.html
  -
    scope:
      path: "works"
      type: "posts"
    values:
      categories: [ "works" ]
      permalink: /works/:title.html
