# Site settings
#
title: Roger is a web engineer.
email: hi@rog.gr
description: > # this means to ignore newlines until "baseurl:"
  Hello, I'm Roger and I'm a self-taught software engineer with a big passion for
  JavaScript and client-side interactions. Software should always be a pleasure to
  use.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rog.gr" # the base hostname & protocol for your site
twitter_username: rogeruiz
github_username: rogeruiz

permalink: /:title.html

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: [ "writing" ]
      permalink: /writing/:title.html
  -
    scope:
      path: "dress-code"
      type: "posts"
    values:
      categories: [ "writing", "dress-code" ]
      permalink: /dress-code/:title.html
  -
    scope:
      path: "works"
      type: "posts"
    values:
      categories: [ "works" ]
      permalink: /works/:title.html

# Build settings
#
markdown: redcarpet

# Babel support
#
babel:
  source: _babel

