# Site settings
#
title: Roger is a web engineer.
email: hi@rog.gr
description: > # this means to ignore newlines until "baseurl:"
  I'm Roger, a self-taught software engineer who believes that
  [JavaScript](http://www.ecmascript.org) will consume the earth for
  better or for worse. Agree or disagree, it sure has caused a whole lot
  of _drama_.
goodbye_message: >
  Thanks for stopping by. 👋🏽
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://write.rog.gr" # the base hostname & protocol for your site
twitter_username: rogeruiz
github_username: rogeruiz

permalink: /:title.html

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - LICENSE.md

include:
  - bower_components/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: [ "writing" ]
      permalink: /writing/:title.html
  -
    scope:
      path: "dress-code"
      type: "posts"
    values:
      categories: [ "writing", "dress-code" ]
      permalink: /dress-code/:title.html
  -
    scope:
      path: "works"
      type: "posts"
    values:
      categories: [ "works" ]
      permalink: /works/:title.html
